[[action-mailer]]
= Action Mailer

Even if we mainly use Ruby on Rails to generate web pages, it sometimes
is useful to be able to send an e-mail.

So let’s go and build an example with minimal user management for a web
shop that automatically sends an e-mail to the user when a new user is
created:

[subs=+quotes]
----
$ **rails new webshop**
  [...]
$ **cd webshop**
$ **rails generate scaffold User name email**
  [...]
$ **rake db:migrate**
  [...]
$
----

For the user model we create a minimal validation in the
`app/models/user.rb`, so that we can be sure that each user has a name
and a syntactically correct e-mail address.

[source,ruby]
.app/models/user.rb
----
class User < ActiveRecord::Base
  validates :name,
            presence: true

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end
----

There is a generator with the name `mailer` that creates the files
required for mailing. First, we have a look at the output of the
`rails generate mailer`, without passing any further arguments:

[subs=+quotes]
----
$ **rails generate mailer**
Usage:
  rails generate mailer NAME [method method] [options]

[...]

Example:
========
    rails generate mailer Notifications signup forgot_password invoice

    creates a Notifications mailer class, views, and test:
        Mailer:     app/mailers/notifications.rb
        Views:      app/views/notifications/signup.text.erb [...]
        Test:       test/mailers/notifications_test.rb
$
----

That is just what we are expecting. So let’s now create the mailer
notification:

[subs=+quotes]
----
$ **rails generate mailer Notification**
      create  app/mailers/notification.rb
      create  app/mailers/application_mailer.rb
      invoke  erb
      create    app/views/notification
      create    app/views/layouts/mailer.text.erb
      create    app/views/layouts/mailer.html.erb
      invoke  test_unit
      create    test/mailers/notification_test.rb
      create    test/mailers/previews/notification_preview.rb
$
----

In the file `app/mailers/notification.rb` you will find the controller:

[source,ruby]
.app/mailers/notification.rb
----
class Notification < ActionMailer::Base
end
----

In it, we create a method `new_account(user)``, with which we send the
confirmation e-mail for a new account:

[source,ruby]
.app/mailers/notification.rb
----
class Notification < ApplicationMailer
  def new_account(user)
    @user = user
    mail(to: user.email, subject: "The account #{user.name} is active.")
  end
end
----

Now we create the view for this method. The file name
`app/views/notification/new_account.text.erb` is composed from the
method name and the ending `text.erb`.

[source,erb]
.app/views/notification/new_account.text.erb
----
Hello <%= @user.name %>,

your new account is active.

Have a great day!
  A Robot
----

As we want to send this e-mail afer the create of a User, we still need
add an `after_create` callback which triggers the delivery. That is done
in `app/models/user.rb`:

[source,ruby]
.app/models/user.rb
----
class User < ActiveRecord::Base
  validates :name,
            presence: true

  validates :email,
            presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }

  after_create :send_welcome_email

  private

  def send_welcome_email
    Notification.new_account(self).deliver_later
  end
end
----

Let’s create a new User in the console:

[subs=+quotes]
----
$ **rails console**
Loading development environment (Rails 4.2.1)
>> User.create(name: 'Wintermeyer', email: 'stefan.wintermeyer@amooma.de')
   (0.1ms)  begin transaction
  SQL (1.6ms)  INSERT INTO "users" ("name", "email", "created_at",
  "updated_at") VALUES (?, ?, ?, ?)  [["name", "Wintermeyer"], ["email",
  "stefan.wintermeyer@amooma.de"], ["created_at", "2015-04-29
  16:37:13.138548"], ["updated_at", "2015-04-29 16:37:13.138548"]]
Enqueued ActionMailer::DeliveryJob (Job ID:
f27145aa-7486-4414-adc5-bd9de3fad056) to Inline(mailers) with arguments:
"Notification", "new_account", "deliver_now", gid://webshop/User/1
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?
  LIMIT 1  [["id", 1]]
Performing ActionMailer::DeliveryJob from Inline(mailers) with arguments:
"Notification", "new_account", "deliver_now", gid://webshop/User/1
  Rendered notification/new_account.text.erb within layouts/mailer (3.0ms)

Notification#new_account: processed outbound mail in 287.6ms

Sent mail to stefan.wintermeyer@amooma.de (19.0ms)
Date: Wed, 29 Apr 2015 18:37:13 +0200
From: from@example.com
To: stefan.wintermeyer@amooma.de
Message-ID: <554108b98175d_59553fefddc601f8557ed@MAC-00020.local.mail>
Subject: The account Wintermeyer is active.
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello Wintermeyer,

your new account is active.

Have a great day!
  A Robot

Performed ActionMailer::DeliveryJob from Inline(mailers) in 309.01ms
   (1.2ms)  commit transaction
=> #<User id: 1, name: "Wintermeyer", email: "stefan.wintermeyer@amooma.de",
created_at: "2015-04-29 16:37:13", updated_at: "2015-04-29 16:37:13">
>> exit
$
----

That was straightforward. In the development mode we see the e-mail in
the log. In production mode it would be send to the configured SMTP
gateway.

[[configuring-the-e-mail-server]]
== Configuring the E-Mail Server

Rails can use a local sendmail or an external SMTP server for delivering
the e-mails.

[[sending-via-local-sendmail]]
=== Sending via Local Sendmail

If you want to send the e-mails in the traditional way via local
`sendmail`, then you need to insert the following lines into your
configuration file `config/environments/development.rb` (for the
development environment) or `config/environments/production.rb` (for
your production environment):

[source,ruby]
.config/environments/development.rb
----
config.action_mailer.delivery_method = :sendmail
config.action_mailer.perform_deliveries = true
config.action_mailer.raise_delivery_errors = true
----

[[sending-via-direct-smtp]]
=== Sending via Direct SMTP

If you want to send the e-mail directly via a SMTP server (for example
Google Mail), then you need to insert the following lines into your
configuration file `config/environments/development.rb` (for the
development environment) or `config/environments/production.rb` (for
your production environment):

[source,ruby]
.config/environments/development.rb
----
config.action_mailer.delivery_method = :smtp
config.action_mailer.smtp_settings = {
  address:              "smtp.gmail.com",
  port:                 587,
  domain:               'example.com',
  user_name:            '<username>',
  password:             '<password>',
  authentication:       'plain',
  enable_starttls_auto: true  }
----

Of course you need to adapt the values for `:domain`, `:user_name` and
`:password` in accordance with your configuration.

[[custom-x-header]]
== Custom X-Header

If you feel the urge to integrate an additional X-header then this is no
problem. Here is an example for expanding the file
`app/mailers/notification.rb`:

[source,ruby]
.app/mailers/notification.rb
----
class Notification < ApplicationMailer
  def new_account(user)
    @user = user
    headers["X-Priority"] = '3'
    mail(to: user.email, subject: "The account #{user.name} is active.")
  end
end
----

This means the sent e-mail would look like this:

[source,text]
----
Sent mail to stefan.wintermeyer@amooma.de (50ms)
Date: Wed, 30 May 2012 17:35:21 +0200
From: from@example.com
To: stefan.wintermeyer@amooma.de
Message-ID: <4fc63e39e356a_aa083fe366028cd8803c7@MacBook.local.mail>
Subject: The new account Wintermeyer is active.
Mime-Version: 1.0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Priority: 3

Hello Wintermeyer,

your new account is active.

Have a great day!
  A Robot
----

[[html-e-mails]]
== HTML E-Mails

Creating HTML e-mails is really easy. Please create the file
`app/views/user_mailer/new_account.html.erb` with the following content:

[source,erb]
.app/views/user_mailer/new_account.html.erb
----
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <p>Hello <%= @user.name %>,</p>

    <p>your new account is active.</p>

    <p><i>Have a great day!</i></p>
    <p>A Robot</p>
  </body>
</html>
----

If you now create a user, the log file `log/development.log` will show
you what was rendered and the e-mail that was sent:

[source,text]
----
Rendered notification/new_account.html.erb within layouts/mailer (0.7ms)
[ActiveJob] [ActionMailer::DeliveryJob] [a819b266-e084-4b26-9041-7e24aa5e2a9f]
Rendered notification/new_account.text.erb within layouts/mailer (0.6ms)
[ActiveJob] [ActionMailer::DeliveryJob] [a819b266-e084-4b26-9041-7e24aa5e2a9f]
Notification#new_account: processed outbound mail in 33.0ms
[ActiveJob] [ActionMailer::DeliveryJob] [a819b266-e084-4b26-9041-7e24aa5e2a9f]
Sent mail to stefan.wintermeyer@amooma.de (7.4ms)
[ActiveJob] [ActionMailer::DeliveryJob] [a819b266-e084-4b26-9041-7e24aa5e2a9f]
Date: Wed, 29 Apr 2015 18:48:00 +0200
From: from@example.com
To: stefan.wintermeyer@amooma.de
Message-ID: <55410b401413d_599d3fefddc601f855944@MAC-00020.local.mail>
Subject: The account Wintermeyer is active.
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_55410b40123ab_599d3fefddc601f8558c3";
 charset=UTF-8
Content-Transfer-Encoding: 7bit
X-Priority: 3


----==_mimepart_55410b40123ab_599d3fefddc601f8558c3
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hello Wintermeyer,

your new account is active.

Have a great day!
  A Robot

----==_mimepart_55410b40123ab_599d3fefddc601f8558c3
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<html>
  <body>
    <!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <p>Hello Wintermeyer,</p>

    <p>your new account is active.</p>

    <p><i>Have a great day!</i></p>
    <p>A Robot</p>
  </body>
</html>
  </body>
</html>

----==_mimepart_55410b40123ab_599d3fefddc601f8558c3--
----

Rails has automatically generated an e-mail in the MIME format
`multipart/alternative`, as the view was present both in the format
`html.erb` and `text.erb`.

[[attachments]]
== Attachments

E-mail attachments are also defined in the controller.

As an example we add in `app/mailers/notification.rb` the Rails image
`app/assets/images/rails.png` to an e-mail as attachment:

[source,ruby]
.app/mailers/notification.rb
----
class Notification < ApplicationMailer
  def new_account(user)
    @user = user
    attachments['rails.png'] =
      File.read("#{Rails.root}/app/assets/images/rails.png")
    mail(to: user.email, subject: "The account #{user.name} is active.")
  end
end
----

[[inline-attachments]]
=== Inline Attachments

For _inline attachments_ in HTML e-mails, you need to use the method
inline when calling `attachments`. In our example controller
`app/mailers/notification.rb`:

[source,ruby]
.app/mailers/notification.rb
----
class Notification < ApplicationMailer
  def new_account(user)
    @user = user
    attachments.inline['rails.png'] =
      File.read("#{Rails.root}/app/assets/images/rails.png")
    mail(to: user.email, subject: "The account #{user.name} is active.")
  end
end
----

In the HTML e-mail, you can access the hash `attachments[]` via
`image_tag`. In our example the
`app/views/notification/new_account.html.erb` would look like this:

[source,erb]
.app/views/notification/new_account.html.erb
----
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
  </head>
  <body>
    <%= image_tag attachments['rails.png'].url, :alt => 'Rails Logo' %>
    <p>Hello <%= @user.name %>,</p>

    <p>your new account is active.</p>

    <p><i>Have a great day!</i></p>
    <p>A Robot</p>
  </body>
</html>
----

[[further-information]]
== Further Information

The Rails online documentation has a very extensive entry on
ActionMailer at http://guides.rubyonrails.org/action_mailer_basics.html.
